### ISSUE TITLE
Release `v0.1.0`

### ISSUE THREAD

**Issue by abrisco** [abrisco/cargo-bazel#8]
Release `v0.1.0` will be the first release that is generally tested and ready for wider use. Until then, changes will continue to be applied to `v0.0`. These changes may be breaking as `v0.0` does not currently follow proper semantic versioning.

## Changes Required

- [ ] Unit testing for all (or nearly all) modules. (#44)
- [x] `x86_64-pc-windows-msvc` support (#5)
- [x] Use an existing local crate index to get registry URLs (#24)
- [x] Fix inconsistencies in rendered library names (#7)
- [x] ~~Actually enable platform filtering (#42)~~
- [x] Ensure the lockfile has no local mods (#66)
